// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/analyze": {
    params: {};
  };
  "/report/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/dashboard" | "/analyze" | "/report/:id" | "/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/analyze.tsx": {
    id: "routes/analyze";
    page: "/analyze";
  };
  "routes/report.tsx": {
    id: "routes/report";
    page: "/report/:id";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};